### ISSUE TITLE
Wsparcie globalnego parametru `padding`

### ISSUE THREAD

**Issue by krasnoludkolo** [krasnoludkolo/wykop-sdk-reborn#40]
https://www.wykop.pl/dla-programistow/apiv2docs/przekazywanie-parametrow/

**Comment by selfisekai** [comment]
globalny parametr `padding` nie istnieje, APIv2 nie ma wsparcia dla JSONP, a nawet gdyby istniał to JSONP jest bezużytecznie poza przeglądarką. wziął się w dokumentacji z tego, że był w API v1, i jak robili kopiuj-wklej to nie usunęli.
przykładowy URL żeby zobaczyć że nie działa: https://a2.wykop.pl/Profiles/AvailableColors/appkey/aNd401dAPp/padding/michal_bialek_wciaga_rogale

**Comment by krasnoludkolo** [comment]
iksde, wcale mnie to nie dziwi, przyjrzę się temu jeszcze i jak faktycznie tak jest to zamknę
