### ISSUE TITLE
Propozycja: przeniesienie Wiki do repozytorium

### ISSUE THREAD

**Issue by mateuszjablonski** [krasnoludkolo/wykop-sdk-reborn#73]
Fajnie byłoby mieć całą dokumentację w repozytorium, w folderze `documentation` w formie plików Markdown, żeby:
- mieć do nich dostęp bezpośrednio z edytora podczas pracy z repo
- mieć możliwość ich zmiany/aktualizacji podczas rozwijania nad repo

**Comment by krasnoludkolo** [comment]
Spoko pomysł, postaram się zrobić w wolnej chwili

**Comment by KORraNpl** [comment]
@mateuszjablonski Generalnie Wiki to też repo z plikami .md :) Wystarczy dodać `.wiki` do nazwy repozytorium przy klonowaniu, np. `git clone git@github.com:krasnoludkolo/wykop-sdk-reborn.wiki`

**Comment by mateuszjablonski** [comment]
@KORraNpl o rzeczywiście, nie wiedziałem. No to zamykam temat, bo dokumentacja de facto JEST na repo
